### ISSUE TITLE
"Close Left" closes everything

### ISSUE THREAD

**Issue by jkovalsky** [funfried/nb-editor-close-left-right#32]
The nb-editor-close-left-right-1.0.5.nbm does not work as expected. I don't see any Close Right action, and Close Left closes all opened tabs instead of just the desired ones. Tested in:

Product Version: Apache NetBeans IDE 19
Java: 19.0.2; OpenJDK 64-Bit Server VM 19.0.2+7-44
Runtime: OpenJDK Runtime Environment 19.0.2+7-44
System: Linux version 5.15.0-100-generic running on amd64; UTF-8; cs_CZ (nb)

**Comment by funfried** [comment]
Hi @jkovalsky,

First of all thanks for testing! Sounds weird to me as the plugin seems to work in the latest version and I tested it even with NetBeans 12, but I'll have a look at it myself and see what I can do to make it work in NetBeans 19 again.

Cheers,
Fabian

**Comment by funfried** [comment]
Hi @jkovalsky,

I checked and I'm pretty sure this bug is not related to a special NetBeans version, it seems to be a general issue with that version. I think I found a solution for this issue and will provide a fixed version soon.

Thanks for testing my plugin and for your work at the NetBeans plugin center! And sorry for obviously not testing it myself as good as I should.

Cheers,
Fabian
